### PR TITLE
Add ElasticSearch AWS Cloud Plugin

### PR DESCRIPTION
**Pull request by notthatbreezy**
This commit installs the ElasticSearch Cloud Plugin for AWS
which can be used to take snapshots of indices and push them
to S3

### CODE REVIEW

**Comment by jwalgran** [comment]
Referencing an AWS-specific plugin in this general purpose role feels a little like mixing concerns. Is creating a separate `ansible-elasticsearch-aws-cloud` role too pedantic?

**Comment by ddohler** [comment]
I have kind of the same thought -- that role could include all the configuration that isn't here.

**Comment by notthatbreezy** [comment]
I debated this before writing it and discussed it with @hectcastro. My rationale for including it with the elasticsearch role is that the version of the plugin is tied closely with the version of elasticsearch so that while it wouldn't be _impossible_ for the two to get out of sync by keeping things together, it would be _harder_.

Having them in separate roles would make that mistake easier, in my opinion. If we don't want to include it here, I'd probably just put in the project I need this on since it is only one command. If this had to install a lot of other dependencies or make changes to elasticsearch configuration, I would agree that keeping them separate would be a good idea.

**Comment by hectcastro** [comment]
A compromise might be to make it `elasticsearch_plugins: []`, but still push individual plugin configuration up to the user. This would kinda mirror how the existing `collectd` role works.

**Comment by ddohler** [comment]
That makes sense to me; I kind of like the `elasticsearch_plugins` idea but since we only have the one right now that might be overkill at this point. I think this is fine then.

**Comment by hectcastro** [comment]
Is this good to merge?

**Comment by notthatbreezy** [comment]
Trying the suggested changes now -- running into some issues with getting the command right with a list of objects but think it's just a YAML syntax thing.

**Comment by notthatbreezy** [comment]
Not sure this is going to work -- here's what I've been trying:

``` yaml
- name: Install ElasticSearch Plugins
  command: {{ item.command }}
           chdir={{ item.directory }}
           creates={{ item.creates }}
  with_items: elasticsearch_plugins
```

with this for `elasticsearch_plugins`:

``` yaml
elasticsearch_plugins:
  - { command: "bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1",
      directory: "/usr/share/elasticsearch",
      creates: "/usr/share/elasticsearch/plugins/cloud-aws/elasticsearch-cloud-aws-2.4.1.jar" }
```

But ansible tells me that there is a syntax error. It seems to have trouble parsing options after the command. If I omit the options then the command runs, but I can't do the check for creates or directory.

This may be a case of trying to do too much with a base role, I ended up just inheriting this role and letting users handle installation which is what I did to get around this issue. If there aren't objections should probably just close this.

**Comment by hectcastro** [comment]
+1 to close.

**Pull request closed without merging**
